# config.yaml
data:
  gold_csv: "data/merge_data/merged_gold_15min_TH_TIME.csv"
  gold_5min_merged: "data/merge_data/merged_gold_5min_TH_TIME.csv" 
  gold_15min_merged: "data/merge_data/merged_gold_15min_TH_TIME.csv"
  news_csv: "data/news_data/gold_macro_news_v1.csv"
  external_csv: "data/premium_hsh/Premium_Calculated_Feb_Apr.csv"

backtest:
  timeframe: "30m"
  
  # --- โหมดที่ 1: กำหนดช่วงเวลาชัดเจน (Train / Test Split) ---
  start_date: "2026-01-01"
  end_date: "2065-01-03"
  
  # --- โหมดที่ 2: ดึงข้อมูลล่าสุดย้อนหลัง ---
  # ถ้าใช้โหมดนี้ ให้ลบค่า start_date/end_date ทิ้ง หรือใส่ค่าเป็น "" (ว่างเปล่า)
  days: 
  
  react_max_iter: 1

llm:
  provider: "gemini"
  model: "" # ปล่อยว่างเพื่อใช้ default

paths:
  cache_dir: "output/BIGtest/backtest_cache_main_version8"
  output_dir: "output//BIGtest/backtest_results_main"
